name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Profile
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./3d-profile-settings.json

      - name: Move generated SVG
        run: |
          mv ./profile-3d-contrib/profile-3d.svg ./profile-3d.svg
          rm -rf ./profile-3d-contrib

      - name: Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update 3D profile contribution graph" && git push)